### ISSUE TITLE
No way to choose template version

### ISSUE THREAD

**Issue by Yajo** [timothycrosley/cruft#10]
It would be great to add a CLI arg that lets the user choose a commit/branch/tag from where to fill the project.

**Comment by pawamoy** [comment]
Like the `link` command I guess, but for project creation. Maybe this is already implemented? Try with `cruft create http://url.to/template commit`

**Comment by samj1912** [comment]
AFAICT link lets you choose the commit which you think your current project is on - but `cruft update` updates to the latest commit. What I think Yajo wants is a way to update to a different commit or branch?
