### ISSUE TITLE
Config file flag --config_file broken due to type hinting

### ISSUE THREAD

**Issue by veaviticus** [timothycrosley/cruft#11]
The `--config_file` flag cannot be used due to the type hinting provided.

See this line: https://github.com/timothycrosley/cruft/blob/374b60ef55e35c7af6319346892780b0b729edde/cruft/api.py#L36

You can't use `typing.Optional` or `typing.Union` with the Hug arg parser, you need to use either `hug.types.one_of` or simply set the type to `str` and default the value to None (which might break mypy or other type validators).

Reproduction:
1. Create a config file with projectName and projectSlug
2. Run as follows
```
$ cruft create --config_file=config.yml -n $URL

usage: cruft [-h] [-o OUTPUT_DIR] [-c CONFIG_FILE] [-d] [-e EXTRA_CONTEXT]
             [-n] [-ov]
             template_git_url
cruft: error: argument -c/--config_file: invalid typing.Union[str, NoneType] value: 'config.yml'
```

**Comment by lsorber** [comment]
Same issue here, was going to post it but happy to see you've already done the work @veaviticus :-)
