### ISSUE TITLE
Can't get update to work on windows

### ISSUE THREAD

**Issue by pawamoy** [timothycrosley/cruft#16]
Even after having tweaked the code to get rid of #12 and #13, it seems that the patch command does not do what is expected. The diff shows lines added, lines removed, and a new file added, but after the command, only the commit sha in cruft.json has changed.

If I look at the output, it's like cruft/patch is patching the temporary files instead of the project files. I think it's because of the `"-d", os.path.sep` I added to the patch command... So in one case I get "ignoring potentially dangerous file" and in the other the wrong files are patched 😢

**Comment by pawamoy** [comment]
The problem was actually coming from a discrepancy between path separators. The diff had `\\` while the temp paths had only one `\`.


Solved it with this change on line 205 of `api.py`:
```diff
-diff = diff.replace(str(old_main_directory), "").replace(str(new_main_directory), "")
+diff = diff.replace("\\\\", "\\").replace(str(old_main_directory), "").replace(str(new_main_directory), "")
```

Now the update works as expected.

**Comment by pawamoy** [comment]
Hello! Thanks for the commit, unfortunately I think it was not enough to prevent introducing other bugs, sorry for not realizing that earlier.

Indeed, if the diff contents (not the files paths) contain backslashes, they will be corrupted by the replace as well. The replace should only occur on the files paths, so maybe this should be done with a regex replace instead.

I am not sure how to get this right with few lines of code.

**Comment by samj1912** [comment]
Clsoing in favor of #41
