### ISSUE TITLE
Relative paths are not supported

### ISSUE THREAD

**Issue by frafra** [timothycrosley/cruft#23]
`cruft check` can fail if the project has been created with a relative path.

Cruft version: 1.1.2.

**Works** as expected:
- `cruft create --no_input $PWD/cookiecutter-custom-template`
- `cruft create --no_input file://$PWD/cookiecutter-custom-template`

**Fails** when running `cruft check`:
- `cruft create --no_input cookiecutter-custom-template`

**Comment by samj1912** [comment]
Should be fixed with #36
