### ISSUE TITLE
Support for Directory as there are multiple templates in single repo

### ISSUE THREAD

**Issue by appunni-dishq** [timothycrosley/cruft#26]
I am having a specific use case where we are trying to maintain the templates for our company in single repo. But cruft doesn't support directory option cookiecutter does. I am working on a PR to do this

**Comment by Zeitsperre** [comment]
@appunni-dishq I can't help but notice you've registered https://pypi.org/project/pycruft/. I was taken for a loop for quite a bit. I'm guessing you want to maintain a fork?

**Comment by appunni-m** [comment]
Not specifically it was just for one time. If you are merging this I am happy to delete it. Again I was on a deadline and installing using poetry was such a headache. I didn't want to put my team mates through it so I just published the wheel. I can take it down if possible.

**Comment by timothycrosley** [comment]
This is fixed in 1.2.0 thanks to @appunni-m 

Thanks!

~Timothy

**Comment by appunni-dishq** [comment]
pycruf deleted @Zeitsperre  Thanks @timothycrosley
