### ISSUE TITLE
Move the CLI from hug to click

### ISSUE THREAD

**Issue by samj1912** [timothycrosley/cruft#31]
Disclaimer - this is just a suggestion. Feel free to close it. click is IMHO may be a better suited framework for creating CLIs than hug. I think where hug really shines is for creating web APIs but for clis I think click has a competitive edge since it was designed with just CLI applications in mind. Click supports better documentation, input types and has click.testing for testing support. It also handles type annotations better than hug. I know hug is maintained by @timothycrosley and since cruft is your project you may want to use it. 

Other benefits are that cookiecutter itself use click. This way we can avoid adding another dependency for our downstream users and possibly reuse more of cookiecutter internals, making the cruft wrapping logic even thinner. This will allow for better compatibility with cookiecutter.

**Comment by samj1912** [comment]
If this is okay to do, I am willing to do the migration.

**Comment by timothycrosley** [comment]
How would you feel about using typer instead? https://github.com/tiangolo/typer In theory, since it is backed by click it should maintain good interoperability with cookiecutter, while maintaining the conciseness of a hug CLI

**Comment by samj1912** [comment]
Typer is great as well! Absolutely a fan of all of @tiangolo's projects :) I will make the move to typer in the next PR
