### ISSUE TITLE
Use git apply instead of `patch`

### ISSUE THREAD

**Issue by samj1912** [timothycrosley/cruft#33]
patch doesn't seem to handle file renames and deletions. Is there any reason why we avoid using `git apply`? We already use `git diff` which means we assume that the user has `git` installed. `git apply` works in a similar fashion across all systems and also shows up merge conflicts if the project folder being updated is a git repo. `git apply` also doesn't need the output project to be a git repo.

**Comment by timothycrosley** [comment]
`git apply` is what I had tried at first, but I had trouble getting it working! I likely was doing something wrong - if you can get it to work, I say go for it!
