### ISSUE TITLE
Drop support for windows? (Cruft will still be available with WSL)

### ISSUE THREAD

**Issue by samj1912** [timothycrosley/cruft#39]
`cruft update` currently doesn't work with windows. Given that is the main selling point of `cruft` I think we should drop windows support. I have a couple of reasons for doing so -

- Cookiecutter and cruft are dev tools
- Windows doesn't really come with a git executable by default it doesn't make sense to have windows support.
- For windows users who program - they can use WSL anyway.
- I don't have a Windows laptop to test/develop windows code. I am guessing @timothycrosley doesn't have one either

This will reduce a lot of code in the repo and allow us to focus on environments which are used by devs.

**Comment by samj1912** [comment]
CC @pawamoy who created the original windows issues

**Comment by pawamoy** [comment]
Yup, just look at https://github.com/copier-org/copier/pull/224, Python+Git+Windows is a PITA to deal with. The thing is, sometimes developers work on Windows machines against their will, with no WSL/Docker support. These developers will be left out. I don't think they represent a large part of Cookiecutter/Cruft user base however, so it should be fine.

**Comment by samj1912** [comment]
@pawamoy can you confirm that `cruft update` currently doesn't work on Windows. If so this seems like a clear way forward and I can open an issue to consider adding windows support back properly.

**Comment by timothycrosley** [comment]
I'm very happy to drop support for now. I do have a windows virtual machine I keep servicable just because some of my other projects (isort in particular) have official windows support, but I like to avoid using it as much as possible! If we get a lot of issue in the future, like @samj1912  said, we can revisit and re-add support.
